### ISSUE TITLE
Research data sources and models

### ISSUE THREAD

**Issue by Riezebos** [rodekruis/Automated-flood-extent-mapping#2]
We are now assuming we will use Sentinel-2.

- What are the alternatives?
- Are they compatible/convertable?
- What are the differences? Resolution, frequency of updates, ease of access, cost?
```[tasklist]
### Tasks
- [ ] How can we differentiate between regular water bodies and flood? Does sen1floods11 include this?
- [ ] Which dataset can we use to validate accuracy of flood mapping of models we use? (not just water/non-water)
- [x] Can we find alternative models that use Sentinel-1 (radar) instead of Sentinel-2 (optical) so that we are not blocked by cloud cover?
```

**Comment by Riezebos** [comment]
Based on current information it looks like the one shared by Jacopo is great:
https://huggingface.co/spaces/ibm-nasa-geospatial/Prithvi-100M-sen1floods11-demo

Are there alternatives?
What are the pros/cons?

**Comment by Riezebos** [comment]
Some findings:
ESRI/ArcGIS has a model for this:
- https://www.esri.com/arcgis-blog/products/arcgis/imagery/flood-inundation-mapping-using-radar-ai/
- https://developers.arcgis.com/python/samples/flood-inundation-mapping-using-sar-data-and-deep-learning/

NVIDIA did some open source work:
- https://ar5iv.labs.arxiv.org/html/2107.08369
- https://github.com/sidgan/ETCI-2021-Competition-on-Flood-Detection

Copernicus publicshed a paper as well:
- https://ieeexplore.ieee.org/document/10295008
- https://isprs-archives.copernicus.org/articles/XLII-3-W4/109/2018/isprs-archives-XLII-3-W4-109-2018.pdf

**Comment by Riezebos** [comment]
Copernicus flood dataset, maybe it is this one?
https://emergency.copernicus.eu/mapping/ems/p05-modelled-flood-extent-major-events

**Comment by Riezebos** [comment]
Ok I looked a little bit more into the links I sent before, and appararently Nasa had a competition in 2021 to do exactly what we want to do :)

Here is the competition: https://nasa-impact.github.io/etci2021/
The winner was this team: https://github.com/YZArren/ETCI2021
The second place was the Nvidia repo I sent before: https://github.com/sidgan/ETCI-2021-Competition-on-Flood-Detection

They use Sentinel-1 SAR data so radar not optical. They also distinguish between water bodies and flood.

@Feynlady, could you look into this a bit more and try to get one of these models to work in Colab?

**Comment by Riezebos** [comment]
Another relevant dataset is provided in this challenge (shared by Jacopo):
https://ieee-dataport.org/competitions/2024-ieee-grss-data-fusion-contest-flood-rapid-mapping
